### ISSUE TITLE
KDE Wayland selection issue

### ISSUE THREAD

**Issue by KrisAphalon** [thenaterhood/gscreenshot#177] opened 2023-10-13 13:45 UTC
I have a weird issue on Wayland. When running `gscreenshot` from the terminal, everything works as expected*. But when I run it without the terminal and selecting "Take screenshot of selection" option, it hides the program but doesn't give me the selection tool to choose which part of the screen I want. I think it then times out after 60 seconds or something and returns with the full-screen screenshot. That makes making selection screenshots impossible.

I'm running: 
 - 6.5.7-zen4-xanmod1-1, Manjaro (Though in my office on newest stable Fedora I also had this problem)
 - plasma desktop 5.27.8 (KDE)
 - wayland 1.22.0
 - gscreenshot 3.4.1
 - xdg-desktop-portal 1.18.0
 - slurp 1.4.0
 - wl-clipboard 2.2.1
 
 
 \* I have one other irrelevant issue with selection screenshots - it also makes screenshots of the selection tool, but it only works incorrectly on my home machine, so it's probably something I need to setup, or in general test a bit more before I create an issue for it.

**Comment by KrisAphalon** [comment] 2023-10-21 02:43
I created a pull request with a fix for it. I also found out why I have the screenshots of the selection tool on my machine: I have window close animation in my desktop manager and gscreenshot makes screenshots too fast, so it catches the selection tool closing. I'm not sure if it's possible to somehow mitigate that.

**Comment by thenaterhood** [comment] 2023-10-30 01:54
Github has decided I no longer want email notifications, apparently. Didn't see the issue, didn't see the PR. Good thing I looked :)

Thanks for looking into this, that's a weird one and a great catch. The window close animation is an issue I have seen catch the gscreenshot window too and there is some code that tries to prevent it that seems to usually work. Gscreenshot might need something similar when it takes a screenshot after getting a selection.

**Comment by thenaterhood** [comment] 2023-11-29 04:37
I can reproduce the selection tool getting caught in the screenshot. There are a couple of issues open on slurp that sound pretty similar with slurp getting caught in screenshots due to a desktop environment's closing animation. The problem appears to be that slurp finishes and exits cleanly, but the window closing animation finishes after slurp has exited and gscreenshot doesn't have any way of knowing when the animation is done.

Interestingly, I notice that the slop region selection tool (which works on a Wayland KDE session in my setup) isn't subject to the same problem and somehow exits without a closing animation. I don't know if slop works universally under Wayland or if there's something special in KDE or my setup that allows it to work, but it would be super easy to update gscreenshot and allow using slop on a Wayland session.

**Comment by thenaterhood** [comment] 2024-03-07 04:31
I have what I'm hoping should help with this in https://github.com/thenaterhood/gscreenshot/pull/181, feel free to try it out.

I added a small delay between grabbing the wayland selection area and taking the screenshot, and also changed the region selection color to be more transparent so if it does get into the screenshot it should be a little less disruptive.

**Comment by thenaterhood** [comment] 2024-03-17 02:58
Marking this as fixed, as I've released some Wayland improvements. Feel free to re-open if it's still an issue.

**Closed by thenaterhood** 2024-03-17 02:58 UTC
