### ISSUE TITLE
Failed to launch after v2.16.2 update, cache issue?

### ISSUE THREAD

**Issue by KrisAphalon** [thenaterhood/gscreenshot#125] opened 2021-11-15 19:53 UTC
After updating to v2.16.2 version from v2.16.1, gscreenshot refuses to work.

I tried both AUR version and compiling it by myself.
Compiling v2.16.1 works and I can use that version

Traceback for v2.16.2:
```
Traceback (most recent call last):
  File "/usr/bin/gscreenshot", line 33, in <module>
    sys.exit(load_entry_point('gscreenshot==2.16.2', 'gui_scripts', 'gscreenshot')())
  File "/usr/bin/gscreenshot", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

`uname -a`
```
Linux aphalon 5.14.10-1-MANJARO #1 SMP PREEMPT Thu Oct 7 06:43:34 UTC 2021 x86_64 GNU/Linux
```

I'm using X11:
```
>>> import os
>>> os.environ['XDG_SESSION_TYPE']
'x11'
```

I don't know what else to provide, here are some libraries I have installed:

`pacman -Q | grep xlib`
```
python-xlib 0.31-1
```
`pacman -Q | grep scrot`
```
scrot 1.6-2
```
`pacman -Q | grep python`:
[python.txt](https://github.com/thenaterhood/gscreenshot/files/7541334/python.txt)

# UPDATE:
After chaging version in source to 2.16.3 and then back to 2.16.2 it started working. Maybe it was a cache issue? How would that even work? It wasn't working for a few days, and now when I started tinkering with it it started working again. I did install `grim` in the meantime, but it didn't work after installing it.

**Comment by thenaterhood** [comment] 2021-11-16 03:06
Very odd! Maybe a Python cache issue, I'm not sure. The load_entry_point stuff is from setuptools/easy_install. You're not the only one to run into it in general, I've seen it with other Python applications.

I've been meaning to re-examine the build/install for gscreenshot since there's more modern guidance for packaging since I put it together and maybe that's coming due.

**Comment by thenaterhood** [comment] 2021-11-16 03:09
Let's leave this open as a bug so I don't forget. As an amusing aside I sometimes skip "symmetrical" version numbers like 2.16.2 as a random programming...superstition...I suppose and this just reinforces that 😆

**Comment by thenaterhood** [comment] 2021-12-25 04:41
After consulting with the Python documentation and the packaging guidelines from a couple distros for Python packages, gscreenshot is using the currently-suggested approach. There are other methods for packaging Python applications that use other, newer utilities which one might argue are more "modern" but until they start showing up more broadly I don't see a reason to switch to them. I also checked to make sure gscreenshot does not depend on distutils, as that is deprecated and will be removed in an upcoming Python version. I could probably invent a way to do some cache busting that might prevent this but any way I can currently think of would create its own set of annoyances that aren't worth the tradeoff since this seems to be pretty rare.

For now, I'm going to close this out in hopes it was just an odd caching issue or an intermittent problem that's out of my control. I can confirm that this _can_ happen, so I'm not discounting it and I'll continue keep an eye out for it.

**Closed by thenaterhood** 2021-12-25 04:41 UTC
Labels: bug
